.TH "wl_array" 3 "Tue Sep 20 2016" "Version 1.12.0" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_array \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wayland-util\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBalloc\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t wl_array::alloc"

.SS "void* wl_array::data"

.SS "size_t wl_array::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
